name: Nuclei - UserAgent/json/irr

on:
    workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - DAST Scan
        uses: fguisso/nuclei-action@npm
        with:
          target: guisso.dev
          user-agent: Guisso testing 2.0
          json: true
          include-rr: true
          output: nuclei.json

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.json
          path: nuclei.json
