name: Nuclei - Flags

on:
    workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - DAST Scan
        uses: fguisso/nuclei-action@fix-flags
        with:
          target: guisso.dev
          flags: "-exclude-id http-missing-security-headers -debug"

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log
