name: Nuclei - Workflows

on:
    workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - DAST Scan
        uses: fguisso/nuclei-action@npm
        with:
          target: guisso.dev
          workflows: wrkflws
